{% set name = "box-sdk-gen" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/box-sdk-gen-{{ version }}.tar.gz
  sha256: e2409b3612019587d9c609d0f7a1399bcdb7aee2164c7c498e336f1d12b58a4a
  patches:
    - 001_setup_urllib3.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - cryptography >=3
    - pyjwt >=1.7.0
    - requests
    - requests-toolbelt

test:
  imports:
    - box_sdk_gen
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/box/box-python-sdk-gen.git
  summary: '[Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
